I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/script.rpy", line 266, in script call
    call click_stool
  File "game/scripts/blood_analysis.rpy", line 280, in script
    if analyzing["splatter"]:
  File "game/scripts/blood_analysis.rpy", line 280, in <module>
    if analyzing["splatter"]:
KeyError: 'splatter'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/script.rpy", line 266, in script call
    call click_stool
  File "game/scripts/blood_analysis.rpy", line 280, in script
    if analyzing["splatter"]:
  File "C:\Users\olivia\Downloads\renpy-8.3.7-sdk\renpy\ast.py", line 1856, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\olivia\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1218, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\olivia\Downloads\renpy-8.3.7-sdk\renpy\python.py", line 1211, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/scripts/blood_analysis.rpy", line 280, in <module>
    if analyzing["splatter"]:
KeyError: 'splatter'

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
The Studio 1.0
Wed Jul  2 16:07:20 2025
